### ISSUE TITLE
feat: .gitmessage를 추가한다.

### ISSUE THREAD

**Issue by FacerAin** [dnd-side-project/dnd-10th-2-backend#6]
## As-is
- git commit convention 가이드가 gitmessage에 명시되어 있지 않음.

## To-be 
- .gitmessage를 통해 개발 환경에서 git commit convention 가이드 확인 가능
이때 convention 가이드는 아래 문서를 기준으로 함
https://github.com/dnd-side-project/dnd-10th-2-backend/wiki/%EA%B0%9C%EB%B0%9C%EC%9E%90-%EB%A7%A4%EB%89%B4%EC%96%BC-%7C-Git-Commit-Message-%EC%BB%A8%EB%B2%A4%EC%85%98

### 기대 효과
- 개발 중 개발 환경 내에서 git commit convection 확인 및 숙지 가능

### Todo 
- [x]  .gitmessage 작성

### References (optional)
- [blog](https://youngjinmo.github.io/2020/03/gitmessage/)

**Comment by Starlight258** [comment]
gitmessage template입니다!
[.gitmessage.txt](https://github.com/dnd-side-project/dnd-10th-2-backend/files/14083405/gitmessage.txt)

**적용방법**
1. gitmessage.txt 생성 후 내용 붙여넣기
`vim ~/.gitmessage.txt` 
2. gitmessage를 템플릿으로 지정
` git config --global commit.template ~/.gitmessage.txt`
